export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOAD_SCHOLARSHIPS = 'LOAD_SCHOLARSHIPS';
export const SHOW_SCHOLARSHIP = 'SHOW_SCHOLARSHIP';
export const ADD_SCHOLARSHIP = 'ADD_SCHOLARSHIP';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
